_commit: 0.2.0-1-gf590723
_src_path: /home/nlesc/github/jspaaks/copier-template-for-c-projects
add_answers: true
add_assets: true
add_clang_format: true
add_external: true
add_test: true
build_directory: build
c_std: c_std_23
exename: calculator
external_directory: external
libname: operations
libpurpose: both
nested: true
producesexe: true
produceslib: true
projectname: calculator-project
