name: testing

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  testing:
    name: py${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'windows-2025' ]
        python-version: ['3.13']
    steps:

      - name: cmake --version
        run: cmake --version

      - name: Install Criterion
        run: |
          choco install meson -y
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          refreshenv
          Invoke-WebRequest -Uri https://github.com/Snaipe/Criterion/archive/refs/tags/v2.4.2.tar.gz -OutFile Criterion-2.4.2.tar.gz
          tar -xvf Criterion-2.4.2.tar.gz
          cd Criterion-2.4.2
          meson setup build
          meson compile -C build
          meson install -C build

      - name: Get a copy of the repository contents
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Python version
        run: |
          which python
          python --version

      - name: Upgrade pip, setuptools and wheel
        run: python -m pip install --upgrade pip setuptools wheel

      - name: both-nested-with-external
        run: |
          cd both-nested-with-external/calculator-project/build
          cmake ..
          cmake --build .
          cmake --install .
          ./dist/bin/calculator
          ./dist/bin/test_operations -j1 --verbose
