name: testing

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  testing:
    name: py${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-14' ]
        python-version: ['3.13']
    steps:

      - name: cmake --version
        run: cmake --version

      # - name: (macos-14) Install Criterion
      #   run: brew install criterion

      - name: Get a copy of the repository contents
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Python version
        run: |
          which python
          python --version

      - name: Upgrade pip, setuptools and wheel
        run: python -m pip install --upgrade pip setuptools wheel

      # - name: Install the template with its testing dependencies
      #   run: python -m pip install .[testing]

      # - name: (macos-14) Run fuzzy tests
      #   run: CC='gcc-14 -I/opt/homebrew/include -L/opt/homebrew/lib' NFUZZY=100 python -m pytest -ra --verbose
    
      - name: both-nested-with-external 
        run: |
          cd both-nested-with-external/calculator-project
          ls -l
          # cd both-nested-with-external/calculator-project/build
          # cmake ..
          # cmake --build .
          # cmake --install .
          # ./dist/bin/calculator
          # ./dist/bin/test_operations -j1 --verbose
