name: testing

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  testing:
    name: py${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'windows-2022' ]
        python-version: ['3.13']
    steps:

      - name: Install Criterion
        run: |
          choco install meson -y
          choco install llvm -y
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          refreshenv
          Invoke-WebRequest -Uri https://github.com/Snaipe/Criterion/archive/refs/tags/v2.4.2.tar.gz -OutFile Criterion-2.4.2.tar.gz
          tar -xvf Criterion-2.4.2.tar.gz
          cd Criterion-2.4.2
          meson setup build .
          meson install -C build

      - name: Get a copy of the repository contents
        uses: actions/checkout@v4

      - name: both-nested-with-external
        run: |
          cd both-nested-with-external/calculator-project/build
          cmake -DCMAKE_C_COMPILER="clang" ..
          cmake --build .
          cmake --install .
          tree /F
