name: testing

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  testing:
    name: py${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-15' ]
        python-version: ['3.13']
    steps:

      - name: cmake --version
        run: cmake --version

      - name: (macos-15) Install Criterion
        run: |
          brew install criterion

      - name: Get a copy of the repository contents
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Python version
        run: |
          which python
          python --version

      - name: Upgrade pip, setuptools and wheel
        run: python -m pip install --upgrade pip setuptools wheel

      # - name: Install the template with its testing dependencies
      #   run: python -m pip install .[testing]

      # - name: (macos-15) Run fuzzy tests
      #   run: CC='gcc-15 -I/opt/homebrew/include -L/opt/homebrew/lib' NFUZZY=100 python -m pytest -ra --verbose
    
      - name: both-nested-with-external
        env:
          CMAKE_INCLUDE_PATH: /opt/homebrew/include
        run: |
          brew --prefix criterion
          find /opt/homebrew/ -maxdepth 7 -name "*criterion*" 
          cd both-nested-with-external/calculator-project/build
          cmake -DCMAKE_INCLUDE_PATH=/opt/homebrew/Cellar/criterion/2.4.2_2/include/ ..
          cmake --build .
          cmake --install .
          ./dist/bin/calculator
          ./dist/bin/test_operations -j1 --verbose
